### ISSUE TITLE
utils.c: get_arguments.  Undeclared variables

### ISSUE THREAD

**Issue by RodrigoGM** [sciccolella/sasc#1]
Hello Simone,
I would like to use your tool, and have been trying to compile it.  My knowledge of C is practically non-existant.  

I'm following your compile suggestions with an optimization flag i.e. , `gcc -o sasc *.c -std=c99 -g -O3 -lm`.  In both cases, with and without compiler optimization, I consistently get an error in `utils.c`.  Am I missing an argument in the compiling stage ?  What version of GCC are you using ?  I have GCC 4.8.5 on CentOS 7

Any help is most appreciated

Rodrigo

The four compilation approaches have been

```
gcc -o sasc *.c -std=c99 -g -O3 -lm
gcc -o sasc *.c -std=c99 -g -lm
gcc -o sasc *.c -O3 -g -lm
gcc -o sasc *.c -std=c99 -g -O3 -lm -Wimplicit-function-declaration
```

for these, the error mesages roughly the same.  Here's a log of what I get back from `gcc`.  

```bash
(base) bash-4.2$ git clone https://github.com/sciccolella/sasc.git
(base) bash-4.2$ cd sasc/
(base) bash-4.2$ ls
data  LICENSE  mt19937ar.c  mt19937ar.h  README.md  sasc.c  sastep.c  sastep.h  test.txt  tree.c  tree.h  utils.c  utils.h  vector.c  vector.h
(base) bash-4.2$ gcc -o sasc *.c -std=c99 -g -O3 -lm
utils.c: In function ‘get_arguments’:
utils.c:114:5: error: ‘opterr’ undeclared (first use in this function)
     opterr = 0;
     ^
utils.c:114:5: note: each undeclared identifier is reported only once for each function it appears in
utils.c:116:5: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
     while ((c = getopt(cargc, cargsv, "hVm:n:a:b:k:i:e:d:lxr:s:")) != - 1) {
     ^
utils.c:119:37: error: ‘optarg’ undeclared (first use in this function)
                 arguments->m = atoi(optarg);
                                     ^
In file included from utils.c:1:0:
utils.c:165:30: error: ‘optopt’ undeclared (first use in this function)
                 if (isprint (optopt))
                              ^
(base) bash-4.2$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sciccolella** [comment]
Hello Rodrigo,
Thank you for your interest in using our tool. It looks like your issue is due to a wrong argument in the compiler. You followed the instruction for the OSX system, while you are actually using Linux OS.

Try to compile with the following command:
`gcc -o sasc *.c -std=gnu99 -g -O3 -lm`.
In any case please stay tuned, because a newer version of the tool will soon be available.

Best,
Simone.

**Comment by RodrigoGM** [comment]
I see.. Thank you for the correction, it worked very well.

Best,
